Added history inside json response
rodrilima/corona-analytic-api pull request #5
Opened 2020-03-17 19:31 UTC by raphaelkieling

I added a attribute called history (to not break current users) that show the history by date.

```diff
brazil": {
    "date": "16/03/2020",
    "time": "15:50",
    "values": [
      {
        "uid": 11,
        "state": "Rondônia (RO)",
        "cases": 0,
        "deaths": 0,
        "suspects": 2,
        "refuses": 1,
        "broadcast": false,
        "comments": "",
+      "history": [
          {
            "date": "02/03/2020",
            "state_uid": 11,
            "cases": 0,
            "deaths": 0,
            "suspects": 0,
            "refuses": 0,
            "broadcast": false,
            "comments": ""
          },
```

This is very good to use on history charts or to track how much increased per day

2020-03-18 10:59 UTC, rodrilima commented
Amazing. I'll check later and if it's all right I'll do the merge. Thanks !!

2020-03-18 13:50 UTC, victorjordan95 commented
That's exactly what I was going to suggest! :D

2020-03-19 00:21 UTC, rodrilima requested changes
Can you adjust to stay in that structure?
`{
  "world": {},
  "brazil": {},
  "history": {
    "world": []
    "brazil": []
  }
}`
This prevents someone who just wants the current date from having to upload the entire history

2020-03-19 00:56 UTC, raphaelkieling commented
Yes i can, i'll fix that later

2020-03-19 12:01 UTC, raphaelkieling commented
I change:
- iso8601 to date (yes, my commit description i called ISO8091 kkk)
- added history in other attribute (as you described)

2020-03-19 12:04 UTC, raphaelkieling commented
i think that is important have a route to get history from a unique state or country but this can be on another issue to not grow up this

2020-03-19 15:12 UTC, merged

2020-03-19 15:13 UTC, rodrilima commented
Nice. Thanks !!